#!/bin/bash

echo "📧 Test Email Information"
echo "========================"
echo ""
echo "⏰ The Logic App runs on a 5-minute timer and simulates emails automatically."
echo ""
echo "📍 Test email configuration:"
echo "   - TO: ma3u-test@email.de"
echo "   - Subject: Catering inquiry simulation"
echo "   - Content: AI-processed catering request"
echo ""
echo "🔄 The Logic App should trigger within the next 5 minutes."
echo "📊 Monitor the execution with: ./monitor-logic-app.sh"
echo ""
echo "💡 Note: The Logic App simulates email reception based on its timer trigger."