#!/bin/bash

echo "🔧 Fixing Google OAuth Redirect URI Error"
echo "========================================"
echo ""
echo "The error 'redirect_uri_mismatch' means the redirect URI in your Google Cloud"
echo "project doesn't match what the OAuth flow is using."
echo ""
echo "📋 Your OAuth Client Details:"
echo "   Project: jasmin-catering-logicapp"
echo "   Client ID: 540827677104-aa674v8tkrf84mm0f7soos1e6prfce3e.apps.googleusercontent.com"
echo ""
echo "🔧 To fix this issue:"
echo ""
echo "1. Go to Google Cloud Console:"
echo "   https://console.cloud.google.com/apis/credentials?project=jasmin-catering-logicapp"
echo ""
echo "2. Click on your OAuth 2.0 Client ID"
echo ""
echo "3. Under 'Authorized redirect URIs', make sure you have BOTH:"
echo "   ✅ https://developers.google.com/oauthplayground"
echo "   ✅ https://global.consent.azure-apim.net/redirect/gmail"
echo ""
echo "4. Click 'SAVE' at the bottom"
echo ""
echo "5. Wait 1-2 minutes for changes to propagate"
echo ""
echo "6. Then use the OAuth Playground method:"
echo "   a) Go to: https://developers.google.com/oauthplayground"
echo "   b) Click settings (⚙️) → Use your own OAuth credentials"
echo "   c) Enter your Client ID and Secret"
echo "   d) Select Gmail scopes and authorize"
echo ""
echo "🚨 Common Issues:"
echo "   - Missing 'https://' in the URI"
echo "   - Trailing slash at the end"
echo "   - Wrong domain (must be exactly as shown above)"
echo ""
echo "📝 Current redirect URIs in your credentials file:"
cat /Users/ma3u/projects/jasmin-catering-ai-agent/.secret/google-oauth-credentials.json | grep -A 3 "redirect_uris" || echo "File not found"