#!/bin/bash

echo "⚠️  OAuth Client ID Mismatch Detected"
echo "===================================="
echo ""
echo "The refresh token was obtained using the OAuth Playground's default client ID,"
echo "not your custom OAuth credentials."
echo ""
echo "You have two options:"
echo ""
echo "Option 1: Get a new refresh token with YOUR credentials"
echo "-------------------------------------------------------"
echo "1. Go to: https://developers.google.com/oauthplayground"
echo ""
echo "2. Click the gear ⚙️ and make sure to:"
echo "   ✅ Check 'Use your own OAuth credentials'"
echo "   📝 Enter YOUR Client ID: YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com"
echo "   📝 Enter YOUR Client secret: GOCSPX-YOUR_GOOGLE_CLIENT_SECRET"
echo ""
echo "3. Select Gmail API scopes and get a new refresh token"
echo ""
echo ""
echo "Option 2: Use the OAuth Playground's default credentials"
echo "--------------------------------------------------------"
echo "Update your .env to use the OAuth Playground's client ID and secret:"
echo ""
echo "GMAIL_CLIENT_ID=407408718192.apps.googleusercontent.com"
echo "GMAIL_CLIENT_SECRET=GOCSPX-PLAYGROUND_CLIENT_SECRET"
echo ""
echo "⚠️  Note: Option 2 is easier but less secure for production use."
echo ""
echo "Recommendation: Use Option 1 for better security and control."