#!/bin/bash

echo "🔐 Get Gmail Refresh Token"
echo "========================="
echo ""
echo "✅ Using your new OAuth credentials:"
echo "   Client ID: 504203103535-aluf56b51h10q7e2dhp1jqb6b2idh0u7.apps.googleusercontent.com"
echo ""
echo "📋 Steps to get your refresh token:"
echo ""
echo "1. Go to OAuth Playground:"
echo "   👉 https://developers.google.com/oauthplayground"
echo ""
echo "2. Click the settings gear ⚙️ in the top right"
echo ""
echo "3. Check ✅ 'Use your own OAuth credentials'"
echo ""
echo "4. Enter your credentials:"
echo "   OAuth Client ID: YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com"
echo "   OAuth Client secret: GOCSPX-YOUR_GOOGLE_CLIENT_SECRET"
echo ""
echo "5. Close the settings"
echo ""
echo "6. In the left panel, scroll down to 'Gmail API v1' and select:"
echo "   ✅ https://www.googleapis.com/auth/gmail.readonly"
echo "   ✅ https://www.googleapis.com/auth/gmail.modify"
echo ""
echo "7. Click 'Authorize APIs'"
echo ""
echo "8. Sign in with: mabu.mate@gmail.com"
echo ""
echo "9. Grant permissions (click Allow)"
echo ""
echo "10. Click 'Exchange authorization code for tokens'"
echo ""
echo "11. Copy the 'refresh_token' value from the response"
echo ""
echo "12. Add it to your .env file:"
echo "    GMAIL_REFRESH_TOKEN=your_refresh_token_here"
echo ""
echo "📝 Then redeploy with: ./deploy-with-env.sh"