#!/bin/bash

# Generate direct OAuth Playground link with credentials pre-filled
CLIENT_ID="YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com"
CLIENT_SECRET="GOCSPX-YOUR_GOOGLE_CLIENT_SECRET"

echo "🔗 Direct OAuth Playground Link"
echo "=============================="
echo ""
echo "Click this link to go directly to OAuth Playground with your settings:"
echo ""
echo "https://developers.google.com/oauthplayground"
echo ""
echo "Then follow these steps:"
echo ""
echo "1️⃣  Click the gear ⚙️ (OAuth 2.0 configuration)"
echo ""
echo "2️⃣  Enter these values:"
echo "    OAuth Client ID: $CLIENT_ID"
echo "    OAuth Client secret: $CLIENT_SECRET"
echo "    ✅ Check 'Use your own OAuth credentials'"
echo ""
echo "3️⃣  Select Gmail API v1 scopes:"
echo "    ✅ https://www.googleapis.com/auth/gmail.readonly"
echo "    ✅ https://www.googleapis.com/auth/gmail.modify"
echo ""
echo "4️⃣  Click 'Authorize APIs' and sign in with mabu.mate@gmail.com"
echo ""
echo "5️⃣  Click 'Exchange authorization code for tokens'"
echo ""
echo "6️⃣  Copy the refresh_token from the response"
echo ""
echo "📝 Quick copy commands after you get the token:"
echo ""
echo "# Add to .env file:"
echo "echo 'GMAIL_REFRESH_TOKEN=YOUR_TOKEN_HERE' >> .env"
echo ""
echo "# Or update Azure directly:"
echo "az functionapp config appsettings set \\"
echo "  --name jasmin-gmail-functions \\"
echo "  --resource-group jasmin-functions-rg \\"
echo "  --settings GMAIL_REFRESH_TOKEN=\"YOUR_TOKEN_HERE\""