#!/bin/bash

# Gmail OAuth Setup Script for Azure Functions
echo "🔐 Setting up Gmail OAuth for Azure Functions"
echo "==========================================="

# OAuth credentials from the .secret directory
CLIENT_ID="YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com"
CLIENT_SECRET="GOCSPX-YOUR_GOOGLE_CLIENT_SECRET"

echo ""
echo "📋 Your Gmail OAuth Credentials:"
echo "   Client ID: $CLIENT_ID"
echo "   Client Secret: $CLIENT_SECRET"
echo ""
echo "⚠️  IMPORTANT: You need to add a new redirect URI to your Google Cloud project"
echo ""
echo "📝 Steps to get refresh token:"
echo ""
echo "1. Go to Google Cloud Console:"
echo "   https://console.cloud.google.com/apis/credentials?project=jasmin-catering-logicapp"
echo ""
echo "2. Click on your OAuth 2.0 Client ID"
echo ""
echo "3. Add this redirect URI:"
echo "   https://developers.google.com/oauthplayground"
echo ""
echo "4. Save the changes"
echo ""
echo "5. Go to OAuth Playground:"
echo "   https://developers.google.com/oauthplayground"
echo ""
echo "6. Click the settings gear (⚙️) and check 'Use your own OAuth credentials'"
echo ""
echo "7. Enter:"
echo "   OAuth Client ID: $CLIENT_ID"
echo "   OAuth Client secret: $CLIENT_SECRET"
echo ""
echo "8. In Step 1, select these scopes:"
echo "   - https://www.googleapis.com/auth/gmail.readonly"
echo "   - https://www.googleapis.com/auth/gmail.modify"
echo ""
echo "9. Click 'Authorize APIs' and sign in with: mabu.mate@gmail.com"
echo ""
echo "10. Click 'Exchange authorization code for tokens'"
echo ""
echo "11. Copy the refresh_token value"
echo ""
echo "12. Update Azure Function settings:"
echo ""
echo "az functionapp config appsettings set \\"
echo "  --name jasmin-gmail-functions \\"
echo "  --resource-group jasmin-functions-rg \\"
echo "  --settings \\"
echo "    GMAIL_CLIENT_ID=\"$CLIENT_ID\" \\"
echo "    GMAIL_CLIENT_SECRET=\"$CLIENT_SECRET\" \\"
echo "    GMAIL_REFRESH_TOKEN=\"YOUR_REFRESH_TOKEN_HERE\" \\"
echo "    SLACK_TOKEN=\"YOUR_SLACK_TOKEN_HERE\""
echo ""
echo "Or update in Azure Portal:"
echo "https://portal.azure.com/#@/resource/subscriptions/b58b1820-35f0-4271-99be-7c84d4dd40f3/resourceGroups/jasmin-functions-rg/providers/Microsoft.Web/sites/jasmin-gmail-functions/configuration"