#!/bin/bash

# Quick Slack Setup Script
echo "🚀 Slack API Token Quick Setup"
echo "=============================="
echo ""
echo "📱 Step 1: Create Slack App"
echo "   → Go to: https://api.slack.com/apps"
echo "   → Click 'Create New App' → 'From scratch'"
echo "   → Name: 'Jasmin Catering Bot'"
echo "   → Workspace: 'mabured.slack.com'"
echo ""
echo "🔐 Step 2: Set Permissions"
echo "   → Click 'OAuth & Permissions' in sidebar"
echo "   → Add Bot Token Scopes:"
echo "     • chat:write"
echo "     • chat:write.public"
echo "     • channels:read"
echo ""
echo "💾 Step 3: Install & Get Token"
echo "   → Click 'Install to Workspace'"
echo "   → Authorize the app"
echo "   → Copy the 'Bot User OAuth Token' (starts with xoxb-)"
echo ""
echo "💬 Step 4: Add Bot to Channel"
echo "   → In Slack, go to #gmail-inbox"
echo "   → Type: /invite @Jasmin Catering Bot"
echo ""
echo "⚙️ Step 5: Update Azure Function"
echo ""
echo "az functionapp config appsettings set \\"
echo "  --name jasmin-gmail-functions \\"
echo "  --resource-group jasmin-functions-rg \\"
echo "  --settings SLACK_TOKEN=\"xoxb-YOUR-TOKEN-HERE\""
echo ""
echo "🔗 Direct Links:"
echo "   Create App: https://api.slack.com/apps/new"
echo "   Azure Portal: https://portal.azure.com/#@/resource/subscriptions/b58b1820-35f0-4271-99be-7c84d4dd40f3/resourceGroups/jasmin-functions-rg/providers/Microsoft.Web/sites/jasmin-gmail-functions/configuration"